/**
 * scripts/migrate-clerk-to-prod.ts
 *
 * Moves Courtside's users from the Clerk DEVELOPMENT instance to the
 * PRODUCTION instance, and generates the SQL that re-keys Supabase to the
 * new Clerk user ids.
 *
 * Why this exists: every user-content table (reviews, skill_ratings,
 * follows, comments, watched_matches, achievements) references
 * profiles.clerk_user_id — the raw Clerk id. Production Clerk issues NEW
 * ids, so without this remap every existing user would sign in to an empty
 * account.
 *
 * Prereqs (see docs/clerk-production-migration.md):
 *   - A production Clerk instance exists (requires a purchased domain)
 *   - CLERK_SECRET_KEY        = dev instance secret (sk_test_…), in .env.local
 *   - CLERK_PROD_SECRET_KEY   = prod instance secret (sk_live_…), exported in shell
 *
 * Usage:
 *   npx tsx scripts/migrate-clerk-to-prod.ts            # dry run — prints plan
 *   npx tsx scripts/migrate-clerk-to-prod.ts --apply    # creates prod users + writes SQL
 *
 * Output: scripts/output/clerk-id-remap.sql — run it in the Supabase SQL
 * editor. It first converts every FK on profiles(clerk_user_id) to
 * ON UPDATE CASCADE, then updates each profile's clerk_user_id; the child
 * tables follow automatically.
 */

import { config } from "dotenv";
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

config({ path: ".env.local" });

const DEV_KEY  = process.env.CLERK_SECRET_KEY;
const PROD_KEY = process.env.CLERK_PROD_SECRET_KEY;
const APPLY    = process.argv.includes("--apply");

interface ClerkUser {
  id: string;
  username: string | null;
  first_name: string | null;
  last_name: string | null;
  email_addresses: Array<{ id: string; email_address: string }>;
  primary_email_address_id: string | null;
}

async function clerk<T>(key: string, path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`https://api.clerk.com/v1${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Clerk ${res.status} on ${path}: ${body.slice(0, 300)}`);
  }
  return res.json() as Promise<T>;
}

function primaryEmail(u: ClerkUser): string | null {
  const hit = u.email_addresses.find((e) => e.id === u.primary_email_address_id);
  return (hit ?? u.email_addresses[0])?.email_address ?? null;
}

async function main() {
  if (!DEV_KEY?.startsWith("sk_test_")) {
    throw new Error("CLERK_SECRET_KEY (dev, sk_test_…) missing from .env.local");
  }

  // ── 1. Export every user from the dev instance ─────────────────────────
  const devUsers: ClerkUser[] = [];
  for (let offset = 0; ; offset += 100) {
    const page = await clerk<ClerkUser[]>(DEV_KEY, `/users?limit=100&offset=${offset}`);
    devUsers.push(...page);
    if (page.length < 100) break;
  }
  console.log(`Dev instance: ${devUsers.length} users`);
  for (const u of devUsers) {
    console.log(`  ${u.id}  ${primaryEmail(u) ?? "NO EMAIL"}  (@${u.username ?? "-"})`);
  }

  if (!APPLY) {
    console.log("\nDry run only. Re-run with --apply (and CLERK_PROD_SECRET_KEY set) to migrate.");
    return;
  }
  if (!PROD_KEY?.startsWith("sk_live_")) {
    throw new Error("CLERK_PROD_SECRET_KEY (sk_live_…) must be exported to use --apply");
  }

  // ── 2. Create each user in prod (skip if the email already exists) ─────
  const idMap: Array<{ old: string; new_: string; email: string }> = [];
  for (const u of devUsers) {
    const email = primaryEmail(u);
    if (!email) { console.warn(`SKIP ${u.id} — no email address`); continue; }

    const existing = await clerk<ClerkUser[]>(
      PROD_KEY, `/users?email_address=${encodeURIComponent(email)}`
    );
    let prodUser = existing[0];

    if (!prodUser) {
      prodUser = await clerk<ClerkUser>(PROD_KEY, "/users", {
        method: "POST",
        body: JSON.stringify({
          email_address: [email],
          username: u.username ?? undefined,
          first_name: u.first_name ?? undefined,
          last_name: u.last_name ?? undefined,
          skip_password_requirement: true, // they sign in via email code / OAuth
        }),
      });
      console.log(`created  ${email} → ${prodUser.id}`);
    } else {
      console.log(`existing ${email} → ${prodUser.id}`);
    }
    idMap.push({ old: u.id, new_: prodUser.id, email });
  }

  // ── 3. Emit the Supabase remap SQL ─────────────────────────────────────
  const updates = idMap
    .map(({ old, new_, email }) =>
      `  -- ${email}\n  UPDATE profiles SET clerk_user_id = '${new_}' WHERE clerk_user_id = '${old}';`
    )
    .join("\n");

  const sql = `-- Generated by scripts/migrate-clerk-to-prod.ts on ${new Date().toISOString()}
-- Re-keys profiles (and, via cascade, all user content) from dev Clerk ids
-- to production Clerk ids. Run in the Supabase SQL editor. Idempotent:
-- re-running matches no rows once applied.

BEGIN;

-- Convert every FK that references profiles(clerk_user_id) to ON UPDATE
-- CASCADE (preserving each constraint's ON DELETE behavior), so updating
-- the profile id flows to reviews/skill_ratings/follows/comments/
-- watched_matches/achievements automatically.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT con.oid, con.conname, cl.relname AS child_table,
           pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    JOIN pg_class cl  ON cl.oid  = con.conrelid
    JOIN pg_class ref ON ref.oid = con.confrelid
    WHERE con.contype = 'f' AND ref.relname = 'profiles'
      AND EXISTS (
        SELECT 1 FROM pg_attribute a
        WHERE a.attrelid = con.confrelid AND a.attnum = ANY (con.confkey)
          AND a.attname = 'clerk_user_id'
      )
  LOOP
    IF r.def NOT LIKE '%ON UPDATE CASCADE%' THEN
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', r.child_table, r.conname);
      -- Strip any existing ON UPDATE action, keep ON DELETE as-is, append
      -- CASCADE (Postgres accepts ON DELETE / ON UPDATE in either order).
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I %s ON UPDATE CASCADE',
                     r.child_table, r.conname,
                     trim(regexp_replace(r.def, 'ON UPDATE (NO ACTION|RESTRICT|CASCADE|SET NULL|SET DEFAULT)', '')));
    END IF;
  END LOOP;
END $$;

${updates}

COMMIT;
`;

  const outDir = join("scripts", "output");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "clerk-id-remap.sql");
  writeFileSync(outPath, sql);
  console.log(`\nWrote ${outPath} — run it in the Supabase SQL editor, then smoke-test a sign-in.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
